export const states = [
  {
    id: "rumination",
    title: "反复纠结",
    term: "思维反刍",
    description: "已经发生的事情、表达或感受，仍在脑中反复出现。",
    shortDescription: "发生过的事，仍在脑中反复出现。",
    affirmation: "这件事可以先停在这里，我不必现在得到答案。",
    affirmations: [
      "这件事可以先停在这里，我不必现在得到答案。",
      "念头再次回来，也不需要立刻跟随。",
      "让这一段反复，慢慢离我远一点。",
      "此刻，只把注意力留给一次呼吸。",
    ],
    audio: "/audio/rumination.mp3",
    scenes: [
      "一段对话总在脑中重播。",
      "我反复猜测别人当时真正的意思。",
      "我总在重播一个让我后悔的决定。",
      "我知道事情过去了，但脑子停不下来。",
      "我不断寻找一个也许不存在的解释。",
      "我想先把这段反复的念头放远一点。",
    ],
  },
  {
    id: "anticipation",
    title: "对未来没底",
    term: "预期担忧",
    description: "面对尚未确定的结果或即将发生的事情，很难把注意力从未来拉回来。",
    shortDescription: "注意力很难从还未发生的事上回来。",
    affirmation: "未来还没有发生，此刻我只需要照顾下一步。",
    affirmations: [
      "未来还没有发生，此刻我只需要照顾下一步。",
      "不确定可以暂时存在，不必现在填满。",
      "把注意力带回身体正在接触的地方。",
      "下一步很小，也已经足够。",
    ],
    audio: "/audio/anticipation.mp3",
    scenes: [
      "考试、面试或汇报前没底。",
      "我担心明天会发生不好的事情。",
      "我脑中一直排演最糟的可能。",
      "事情还没开始，我已经感到很紧绷。",
      "不确定让我很难休息。",
      "我想把注意力暂时带回现在。",
    ],
  },
  {
    id: "overload",
    title: "思绪过载",
    term: "认知与任务过载",
    description: "事情、信息和要求同时占用注意力，难以排序、选择或判断下一步。",
    shortDescription: "信息与任务同时挤占着注意力。",
    affirmation: "我不需要同时处理一切，只留下眼前的一件事。",
    affirmations: [
      "我不需要同时处理一切，只留下眼前的一件事。",
      "没有被处理的内容，可以先放在一旁。",
      "先让脑海里的声音，彼此离远一点。",
      "现在，只需要辨认最小的一步。",
    ],
    audio: "/audio/overload.mp3",
    scenes: [
      "事情堆在一起，不知道先做什么。",
      "消息和要求不断进来，我无法集中。",
      "每件事都像很重要，我难以取舍。",
      "我脑子很满，却什么也没推进。",
      "我不断切换任务，越来越疲惫。",
      "我需要先让信息安静下来。",
    ],
  },
  {
    id: "blocked",
    title: "难以启动",
    term: "行动启动受阻",
    description: "当前可能仍有一定精力，但任务没有真正进入执行。",
    shortDescription: "有一些精力，却迟迟没有真正开始。",
    affirmation: "开始可以很小，小到只需要一次呼吸和一个动作。",
    affirmations: [
      "开始可以很小，小到只需要一次呼吸和一个动作。",
      "不必完成全部，只靠近第一个动作。",
      "允许身体用自己的速度，从停住走向开始。",
      "做一点点，也是在改变此刻的位置。",
    ],
    audio: "/audio/blocked.mp3",
    scenes: [
      "一直在准备，却没有进入执行。",
      "任务并不难，但我一直在回避它。",
      "我在准备和真正开始之间打转。",
      "我想做事，却像被卡在原地。",
      "想到完整任务，我就失去了行动感。",
      "我愿意尝试一个小到不会失败的开头。",
    ],
  },
  {
    id: "aftershock",
    title: "情绪未平",
    term: "情绪余波",
    description: "事件已经结束或暂时停止，但情绪或身体反应仍在影响现在。",
    shortDescription: "事情停下了，情绪和身体仍有余波。",
    affirmation: "事情停下了，我的身体也可以慢慢停下来。",
    affirmations: [
      "事情停下了，我的身体也可以慢慢停下来。",
      "余下的感受，不需要被催着离开。",
      "每一次呼气，都给身体多一点空间。",
      "我可以等这一阵余波，慢慢经过。",
    ],
    audio: "/audio/aftershock.mp3",
    scenes: [
      "没得到期待的回应，很失落。",
      "刚才的事情让我身体一直发紧。",
      "我表面平静了，心里还在翻涌。",
      "我离开了现场，却仍像身处其中。",
      "情绪退了一些，但还没有真正落下。",
      "我想给身体一点恢复的时间。",
    ],
  },
  {
    id: "low-energy",
    title: "精力不足",
    term: "可用能量不足",
    description: "身体、注意力或动机资源不足，当前需要先判断是恢复，还是轻量启动。",
    shortDescription: "身体、注意或动机暂时不够用。",
    affirmation: "能量不足不是失败，我可以选择恢复，也可以只走一小步。",
    affirmations: [
      "能量不足不是失败，我可以选择恢复，也可以只走一小步。",
      "先感受身体，而不是要求它立刻振作。",
      "恢复与前进，都可以从很小的动作开始。",
      "此刻能做到多少，就先允许多少。",
    ],
    audio: "/audio/low-energy.mp3",
    scenes: [
      "刚醒来，状态还没有启动。",
      "我想休息，却又为休息感到内疚。",
      "注意力很散，身体也没有力气。",
      "我分不清自己需要休息还是需要开始。",
      "我今天已经消耗了很多。",
      "我想先确认此刻真正需要什么。",
    ],
  },
];

export const emotionTerms = [
  { term: "思维反刍", text: "注意力反复回到已经发生的内容。它不等于认真思考，通常不会带来新的信息。", stateId: "rumination" },
  { term: "预期担忧", text: "思绪持续尝试预测尚未发生的结果，以获得确定感。", stateId: "anticipation" },
  { term: "认知负荷", text: "工作记忆同时承载的信息有限，超过容量时，排序和判断都会变难。", stateId: "overload" },
  { term: "行动启动", text: "从计划切换到第一个实际动作，需要单独的注意力和动机资源。", stateId: "blocked" },
  { term: "情绪余波", text: "事件结束后，神经系统和身体反应可能仍需要时间回到较稳定状态。", stateId: "aftershock" },
  { term: "可用能量", text: "此刻可以调动的身体、注意力与动机资源，而不是对能力或意志的评价。", stateId: "low-energy" },
];

const knowledgeTopicsBase = [
  { group: "想法与注意", items: [
    { term: "思维反刍", summary: "反复回到已经发生的事，却很少产生新信息。", myth: "它不等于认真复盘。", evidence: "Level A", source: "Aldao 等，2010；Flavell，1979" },
    { term: "元认知", summary: "注意到“我正在想什么”，而不是自动相信每一个念头。", myth: "它不是强迫自己停止思考。", evidence: "Level E", source: "Flavell，1979" },
    { term: "工作记忆", summary: "我们能同时留在脑中处理的信息容量有限。", myth: "超载不代表能力不足。", evidence: "Level B", source: "Baddeley，1992" },
    { term: "执行功能", summary: "抑制、切换和工作记忆共同支持下一步行动。", myth: "卡住不总是意志薄弱。", evidence: "Level B", source: "Diamond，2013" },
  ]},
  { group: "担忧与不确定", items: [
    { term: "预期担忧", summary: "思绪持续预测未来，希望先获得确定感。", myth: "担心更多不一定准备得更好。", evidence: "Level B", source: "Carleton，2016" },
    { term: "不确定性耐受", summary: "允许部分未知存在，同时仍能采取有限行动。", myth: "它不是对风险不负责。", evidence: "Level B", source: "Carleton，2016" },
    { term: "安全行为", summary: "反复确认或过度准备能短时减压，也可能维持担忧。", myth: "让人安心的行为不一定长期有益。", evidence: "Level E", source: "Rapee 与 Heimberg，1997" },
    { term: "灾难化", summary: "注意力更容易被最坏结果吸引，并高估其概率或代价。", myth: "识别它不代表否认真实风险。", evidence: "Level B", source: "Hofmann 等，2012" },
  ]},
  { group: "行动与能量", items: [
    { term: "行动启动", summary: "从准备切换到第一个动作，本身需要认知资源。", myth: "知道该做什么不等于能立即开始。", evidence: "Level B", source: "Diamond，2013" },
    { term: "行为激活", summary: "先接触小行动和环境反馈，再等待动力出现。", myth: "它不是逼自己保持忙碌。", evidence: "Level A", source: "Ekers 等，2014" },
    { term: "实施意图", summary: "把“想做”改写成“如果遇到 X，我就做 Y”。", myth: "计划句不是执行保证书。", evidence: "Level E", source: "Gollwitzer，1999" },
    { term: "可用能量", summary: "此刻能调用的身体、注意和动机资源。", myth: "它不是对个人能力的评价。", evidence: "Level B", source: "McEwen，1998；Diamond，2013" },
  ]},
  { group: "情绪调节", items: [
    { term: "情绪调节", summary: "改变情绪发生、持续或表达方式的一组过程。", myth: "目标不是控制掉所有情绪。", evidence: "Level E", source: "Gross，1998" },
    { term: "认知重评", summary: "改变对情境意义的理解，从而影响情绪反应。", myth: "它不是强迫乐观。", evidence: "Level A", source: "Buhle 等，2014" },
    { term: "接纳", summary: "允许不舒服存在，同时保留行动选择。", myth: "接纳不等于赞同或放弃改变。", evidence: "Level B", source: "Chawla 与 Ostafin，2007" },
    { term: "表达抑制", summary: "减少外在表达，但内部体验未必同步下降。", myth: "它并非任何场景都不好。", evidence: "Level D", source: "Gross 与 John，2003" },
  ]},
  { group: "身体与恢复", items: [
    { term: "压力评估", summary: "压力来自情境要求与可用资源之间的关系。", myth: "压力并非事件的固定属性。", evidence: "Level E", source: "Lazarus 与 Folkman，1984" },
    { term: "适应性负荷", summary: "长期应对压力可能累积身体系统成本。", myth: "它不能用于自我诊断。", evidence: "Level B", source: "McEwen，1998" },
    { term: "情绪余波", summary: "事件结束后，身体和注意仍可能保持激活。", myth: "恢复较慢不代表你处理失败。", evidence: "Level E", source: "Gross，1998" },
    { term: "呼吸与放松", summary: "缓慢呼吸可能帮助部分人降低当下唤醒水平。", myth: "它不是对所有压力的万能答案。", evidence: "Public Resource", source: "NIH NCCIH；NHS" },
  ]},
  { group: "理解与自我关系", items: [
    { term: "情绪粒度", summary: "更精确地区分和命名正在经历的感受。", myth: "名称越多不等于理解越深。", evidence: "Level B", source: "Kashdan 等，2015" },
    { term: "自我关怀", summary: "困难时减少自我攻击，并保持对现实的诚实。", myth: "它不是放纵或降低标准。", evidence: "Level A", source: "Kirby 等，2017；Neff，2011" },
    { term: "自我肯定", summary: "受威胁时重新连接更广泛的重要价值。", myth: "它不是重复漂亮口号。", evidence: "Level A", source: "Cohen 与 Sherman，2014" },
    { term: "心理灵活性", summary: "在不舒服仍存在时，根据情境和价值调整行动。", myth: "它不是永远保持平静。", evidence: "Level B", source: "Kashdan 与 Rottenberg，2010" },
  ]},
];

const knowledgeDetails = {
  "思维反刍": {
    mechanism: "反刍会让注意力持续黏在原因、后果和自我评价上。它看起来像在解决问题，却常因缺少新信息而形成重复回路，并占用工作记忆。",
    signs: ["同一段对话或决定反复重播", "不断追问“为什么当时会这样”", "思考很久，却没有出现新的可行动信息"],
    practice: "可以先区分：我是在获得新信息，还是只在重复旧内容？若是后者，短暂把注意力放到一个具体感官线索上，往往比命令自己“别想了”更可行。",
    boundary: "偶尔复盘是正常的。只有当反复思考长期影响睡眠、工作或关系时，才值得寻求专业评估。",
  },
  "元认知": {
    mechanism: "元认知让人把念头视为心理事件，而不是必须立即相信或执行的事实。这个距离能为重新选择注意和行动留出空间。",
    signs: ["能说出“我注意到自己正在担心”", "发现念头出现与跟随念头并非同一件事", "可以观察思考过程，而不急于判断对错"],
    practice: "尝试把“事情一定会变糟”改写为“我注意到脑中出现了事情会变糟的预测”。这不是否认风险，而是标明它目前仍是一个念头。",
    boundary: "元认知不是压制思考，也不是要求持续自我监控；过度检查自己的每个念头同样可能增加负担。",
  },
  "工作记忆": {
    mechanism: "工作记忆负责暂时保存并操作信息，容量有限。任务切换、通知和未完成事项都会竞争这部分资源，使排序和判断变慢。",
    signs: ["读完一句话却忘了开头", "同时处理多件事时频繁漏项", "简单选择也需要反复比较"],
    practice: "把需要记住的内容移到纸面或清单中，再只保留当前一步。外部记录不是依赖，而是在减少无必要的内部负荷。",
    boundary: "短时超载不等于记忆能力下降。若记忆变化持续、明显或伴随其他身体症状，应咨询合适的专业人员。",
  },
  "执行功能": {
    mechanism: "执行功能包含抑制自动反应、在任务间切换和维持目标信息。压力、睡眠不足和高负荷都可能暂时削弱这些过程。",
    signs: ["知道下一步，却很难开始", "容易被新刺激带走", "切换任务后很难回到原来的位置"],
    practice: "先把目标改写成一个可以立即看见的动作，例如“打开文件并写下标题”，减少同时需要抑制和规划的内容。",
    boundary: "执行困难不是意志品质判断。它可能来自多种情境因素，单一表现不能用于自我诊断。",
  },
  "预期担忧": {
    mechanism: "担忧试图通过提前模拟未来来降低不确定感，但持续模拟会让威胁保持在注意中心，身体也可能一直处于准备状态。",
    signs: ["不断排演尚未发生的对话", "希望在行动前排除所有意外", "休息时仍在检查未来风险"],
    practice: "把可处理的准备与无法提前解决的未知分开。前者列出一个具体动作，后者先允许它暂时没有答案。",
    boundary: "合理计划有现实价值；问题不在于想到未来，而在于思考是否持续带来新信息和有效行动。",
  },
  "不确定性耐受": {
    mechanism: "耐受不确定并不是喜欢未知，而是在信息不完整时仍能保留行动能力，不把获得百分之百确定当作开始的前提。",
    signs: ["能在保留疑问时做有限决定", "减少反复确认后仍可继续当前任务", "接受部分结果只能等待"],
    practice: "选择一个低风险的小未知，减少一次额外确认，并观察不适如何自然变化。重点是练习承受，而不是证明担心一定不会发生。",
    boundary: "它不适用于需要严格核验的安全、医疗或法律决定；真实风险仍需要相应的信息和专业判断。",
  },
  "安全行为": {
    mechanism: "反复确认、回避或过度准备会立刻降低焦虑，因此容易被强化；但它也可能让人无法发现自己其实能够应对不确定。",
    signs: ["发送信息后不断检查语气", "为低概率情况准备许多备用方案", "必须得到他人保证才能继续"],
    practice: "先识别哪一个动作主要是在换取短暂安心，再选择幅度很小的减少，而不是一次性全部停止。",
    boundary: "安全行为需要结合情境判断。真正降低客观风险的措施不应因为这个概念而被取消。",
  },
  "灾难化": {
    mechanism: "注意系统会优先处理威胁。灾难化发生时，最坏结果不仅更醒目，其发生概率和不可承受程度也可能被同时高估。",
    signs: ["从一个小失误迅速推演到全面失败", "只看到最坏结果，忽略中间可能", "把不舒服等同于无法承受"],
    practice: "分别写下最坏、最好和最可能的结果，再问：如果最可能的情况发生，我能采取哪一步？",
    boundary: "平衡估计不等于盲目乐观，也不应用来淡化真实危险或他人的伤害。",
  },
  "行动启动": {
    mechanism: "开始需要把抽象目标转换为具体动作，并抑制其他竞争行为。任务越模糊、情绪成本越高，启动门槛往往越明显。",
    signs: ["长时间准备工具却没有进入任务", "不断优化计划以推迟第一步", "想到完整任务就失去行动感"],
    practice: "把起点缩到两分钟内可完成，并把完成标准改成“开始过”，而不是“必须做完”。",
    boundary: "小步启动适合降低门槛，但不能替代对过度工作、睡眠不足或身体疾病等根本原因的处理。",
  },
  "行为激活": {
    mechanism: "行为激活强调行动、环境反馈与情绪之间的双向关系：不必总等到有动力，低门槛行动也可能创造新的反馈。",
    signs: ["因情绪低落逐渐减少原有活动", "等待状态变好后才允许行动", "活动范围缩小后获得感进一步减少"],
    practice: "选择一个负担低、与生活方向有关的活动，先记录完成后的实际感受，不要求它必须立刻让心情变好。",
    boundary: "行为激活不是强迫忙碌。严重抑郁、明显功能受损或安全风险需要专业支持。",
  },
  "实施意图": {
    mechanism: "“如果 X，就做 Y”的结构把情境线索与动作预先连接，减少现场重新决定所需的执行资源。",
    signs: ["有目标但总在合适时机到来时忘记", "计划只有愿望，没有触发条件", "每次开始前都重新犹豫"],
    practice: "把“今晚早点休息”改成“如果时钟到 23:00，我就把手机放到书桌充电”。线索和动作都要具体。",
    boundary: "实施意图提高的是触发概率，不是成功保证；不合理的目标不会因为写成句式就变得可行。",
  },
  "可用能量": {
    mechanism: "注意、身体状态、动机与压力共同影响当下可调用资源。可用能量会波动，不应被直接解释为能力或人格。",
    signs: ["同一任务在不同时间难度差异很大", "注意和身体疲劳同时出现", "越责备自己，越难调动资源"],
    practice: "先判断当前更需要恢复还是轻量启动，再选择与资源相称的动作，而不是沿用状态良好时的标准。",
    boundary: "持续或突出的疲劳可能与睡眠、药物或身体健康有关，不能只用心理概念解释。",
  },
  "情绪调节": {
    mechanism: "调节可以发生在情境选择、注意分配、意义解释和表达等不同阶段。有效策略通常依赖情境，而非存在唯一正确方法。",
    signs: ["主动改变注意焦点或环境", "重新理解事件意义", "选择表达、延迟表达或寻求支持"],
    practice: "先问当前目标是什么：降低强度、理解信息、完成任务，还是保护关系？目标不同，合适策略也不同。",
    boundary: "情绪调节不是把所有情绪压低。情绪也可能提供边界、需要和风险信息。",
  },
  "认知重评": {
    mechanism: "重评通过改变对情境意义的解释来影响反应，例如把紧张理解为身体正在为重要任务做准备。",
    signs: ["能看到同一事件不止一种解释", "区分事实与对事实的推断", "新的解释会改变后续行动"],
    practice: "寻找一个同样符合事实、但更完整的解释。它不必积极，只需减少不必要的绝对化。",
    boundary: "重评不应用来合理化伤害、否认不公平或要求自己对一切保持积极。",
  },
  "接纳": {
    mechanism: "接纳减少与内部体验的持续对抗，让注意力从“必须立刻消除不适”转回当下可选择的行动。",
    signs: ["允许不舒服暂时存在", "不再把情绪出现视为失败", "感受仍在，但行为选择变多"],
    practice: "用具体语言描述当下的身体和情绪，而不急着解释原因，例如“胸口发紧，我正在担心”。",
    boundary: "接纳内部感受不等于接受外部伤害，也不妨碍设立边界或改变处境。",
  },
  "表达抑制": {
    mechanism: "表达抑制主要改变外在表现，未必同步改变内部体验；长期高频使用还可能增加认知和关系成本。",
    signs: ["努力不让他人看出情绪", "表面平静但身体仍紧绷", "表达被压住后反复回想"],
    practice: "区分“此刻选择不表达”和“我不允许自己有感受”。前者可以是情境策略，后者更容易形成额外压力。",
    boundary: "在需要安全、专业或暂缓冲突的场景中，控制表达可能是合理选择，不能一概视为有害。",
  },
  "压力评估": {
    mechanism: "压力取决于人如何评估情境要求，以及自己是否拥有足够资源。相同事件对不同人、不同时间可能产生不同压力。",
    signs: ["先判断事情是否威胁重要目标", "随后评估自己能否应对", "资源变化后压力感也随之变化"],
    practice: "把“这件事压力很大”拆成两问：要求具体是什么？我缺少的是时间、信息、支持还是恢复？",
    boundary: "评估模型不是说压力全由想法造成；客观负担、权力关系和资源限制同样真实。",
  },
  "适应性负荷": {
    mechanism: "身体反复应对压力时，多套生理系统会持续调整。长期累积的调节成本被称为适应性负荷。",
    signs: ["长期处于恢复不足的状态", "压力来源反复且难以退出", "睡眠、注意与身体感受同时受影响"],
    practice: "与其只追求一次彻底放松，更值得寻找可重复的恢复窗口，并减少不必要的持续警戒。",
    boundary: "这是群体研究和理论概念，不能根据主观疲劳自行判断生理指标或疾病。",
  },
  "情绪余波": {
    mechanism: "事件结束并不意味着自主神经和注意系统立即恢复。身体可能仍保持激活，需要时间确认环境已经变化。",
    signs: ["离开现场后心跳或肌肉仍紧", "表面平静但注意仍被事件拉回", "情绪强度下降后仍有残留感"],
    practice: "先给身体一个明确的情境转换线索，例如放慢呼气、改变空间或完成一个收尾动作。",
    boundary: "恢复速度存在个体差异。若反应持续强烈、反复侵入或影响日常功能，应考虑专业支持。",
  },
  "呼吸与放松": {
    mechanism: "较慢的呼吸可能影响自主神经活动并降低部分人的当下唤醒水平，但效果因人和情境而异。",
    signs: ["呼吸在压力下变浅或变快", "延长呼气时身体稍有松动", "把注意放到呼吸能暂时稳定焦点"],
    practice: "不必追求很深的吸气，只尝试舒适、缓慢且不过度的节奏；若头晕或不适，应立即恢复自然呼吸。",
    boundary: "呼吸练习不是万能干预。部分惊恐或呼吸疾病用户可能需要更谨慎的指导。",
  },
  "情绪粒度": {
    mechanism: "更精细地命名感受有助于区分需要和行动倾向，例如失落、羞愧、愤怒虽然都不舒服，却指向不同信息。",
    signs: ["不只用“难受”概括所有体验", "能区分情绪、身体感受和想法", "命名后更容易判断下一步需要"],
    practice: "从强度、身体位置和行动冲动三个维度描述感受，再选择一个最接近的词，不要求绝对准确。",
    boundary: "词汇更多不必然代表理解更深；命名应服务于理解，而不是成为新的正确答案压力。",
  },
  "自我关怀": {
    mechanism: "自我关怀通常包含对痛苦的觉察、共同人性和较少攻击性的自我回应，目的是在困难中保持支持与诚实。",
    signs: ["承认自己正在困难而非立刻责备", "用对待可信朋友的标准回应自己", "保持边界和责任，同时减少羞辱"],
    practice: "把自我批评句写下来，再改写成既不回避责任、也不贬低人格的一句话。",
    boundary: "自我关怀不是免除后果或降低所有标准；它关注的是用何种方式面对需要改变的事实。",
  },
  "自我肯定": {
    mechanism: "自我肯定通过重新连接更广泛的重要价值，减少单一威胁对整体自我评价的占据，而非简单重复积极口号。",
    signs: ["受挫时仍能想起其他重要身份和价值", "不把一次失败扩展为整体否定", "价值提醒帮助恢复问题解决"],
    practice: "选择一个此刻真正重要的价值，写下最近一个与它有关的具体行动，而不是写无法相信的夸张赞美。",
    boundary: "肯定语若与体验差距过大，可能显得空洞。内容需要可信、具体，并允许复杂感受同时存在。",
  },
  "心理灵活性": {
    mechanism: "心理灵活性指在想法和感受变化时，仍能根据现实情境与价值调整注意和行动，而不是被单一策略锁住。",
    signs: ["同一策略无效时愿意更换", "不舒服存在时仍保留有限行动", "能在坚持与放下之间根据情境选择"],
    practice: "问自己：此刻继续对抗、暂时接纳、寻求支持或采取行动，哪一种更接近我真正重视的方向？",
    boundary: "灵活不等于没有原则，也不要求适应所有环境；有时离开或拒绝才是与价值一致的选择。",
  },
};

export const knowledgeTopics = knowledgeTopicsBase.map((topic, topicIndex) => ({
  ...topic,
  items: topic.items.map((item, itemIndex) => ({
    ...item,
    id: `${topicIndex + 1}-${itemIndex + 1}`,
    ...(knowledgeDetails[item.term] ?? {}),
  })),
}));

export const encounterTracks = [
  { id: "white-noise", category: "noise", title: "白噪 · 均匀", note: "连续、平直，不需要跟随旋律", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Whitenoisesound.ogg", loop: true, license: "公有领域", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Whitenoisesound.ogg" },
  { id: "gray-noise", category: "noise", title: "灰噪 · 低缓", note: "较柔和的频谱，适合降低环境干扰", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Gray_noise.ogg", loop: true, license: "公有领域", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Gray_noise.ogg" },
  { id: "white-noise-soft", category: "noise", title: "白噪 · 轻声", note: "短循环、轻量，留出更安静的背景", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/White.Noise.ogg", loop: true, license: "公有领域", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:White.Noise.ogg" },
  { id: "reverie", category: "music", title: "梦 · Rêverie", note: "德彪西钢琴作品，缓慢而有留白", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Reverie.ogg", loop: false, license: "公有领域", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Reverie.ogg" },
  { id: "chopin-nocturne", category: "music", title: "夜曲 · Op. 9 No. 2", note: "肖邦夜曲，柔和而连贯", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Chopin.Nocturne.Es-Dur.opus.9.2.ogg", loop: false, license: "CC0", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Chopin.Nocturne.Es-Dur.opus.9.2.ogg" },
  { id: "bach-cello", category: "music", title: "无伴奏 · 前奏曲", note: "巴赫大提琴组曲，稳定、清晰", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/JOHN_MICHEL_CELLO-J_S_BACH_CELLO_SUITE_1_in_G_Prelude.ogg", loop: false, license: "CC BY-SA 3.0", source: "John Michel / Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:JOHN_MICHEL_CELLO-J_S_BACH_CELLO_SUITE_1_in_G_Prelude.ogg" },
];
